python3 main.py --case 1
python3 main.py --case 2
python3 main.py --case 3
python3 main.py --case 4
python3 main.py --case 5
python3 main.py --case 6
python3 main.py --case 7
python3 main.py --case 8
python3 main.py --case 9
